# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 600)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(320, 150, 321, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(40, -1, 50, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.loginEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.loginEdit.setMaximumSize(QtCore.QSize(225, 16777215))
        self.loginEdit.setObjectName("loginEdit")
        self.horizontalLayout_3.addWidget(self.loginEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(40, -1, 50, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.passwordEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.passwordEdit.setMaximumSize(QtCore.QSize(225, 16777215))
        self.passwordEdit.setObjectName("passwordEdit")
        self.horizontalLayout_2.addWidget(self.passwordEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.enterButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.enterButton.setMinimumSize(QtCore.QSize(0, 30))
        self.enterButton.setMaximumSize(QtCore.QSize(125, 16777215))
        self.enterButton.setObjectName("enterButton")
        self.horizontalLayout.addWidget(self.enterButton)
        self.createButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.createButton.setMinimumSize(QtCore.QSize(0, 30))
        self.createButton.setMaximumSize(QtCore.QSize(125, 16777215))
        self.createButton.setObjectName("createButton")
        self.horizontalLayout.addWidget(self.createButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Логин  "))
        self.label_2.setText(_translate("Form", "Пароль"))
        self.enterButton.setText(_translate("Form", "Войти"))
        self.createButton.setText(_translate("Form", "Создать"))
