# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 971, 531))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.enterButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.enterButton.setMinimumSize(QtCore.QSize(0, 30))
        self.enterButton.setMaximumSize(QtCore.QSize(125, 16777215))
        self.enterButton.setObjectName("enterButton")
        self.horizontalLayout_2.addWidget(self.enterButton)
        self.changeLoginButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.changeLoginButton.setMinimumSize(QtCore.QSize(0, 30))
        self.changeLoginButton.setMaximumSize(QtCore.QSize(125, 16777215))
        self.changeLoginButton.setObjectName("changeLoginButton")
        self.horizontalLayout_2.addWidget(self.changeLoginButton)
        self.changePasswordButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.changePasswordButton.setMinimumSize(QtCore.QSize(0, 30))
        self.changePasswordButton.setMaximumSize(QtCore.QSize(125, 16777215))
        self.changePasswordButton.setObjectName("changePasswordButton")
        self.horizontalLayout_2.addWidget(self.changePasswordButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.verticalLayout.addWidget(self.plainTextEdit)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.saveButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.saveButton.setMinimumSize(QtCore.QSize(0, 30))
        self.saveButton.setMaximumSize(QtCore.QSize(125, 16777215))
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_3.addWidget(self.saveButton)
        self.deleteButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.deleteButton.setMinimumSize(QtCore.QSize(0, 30))
        self.deleteButton.setMaximumSize(QtCore.QSize(125, 16777215))
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout_3.addWidget(self.deleteButton)
        self.deleteAccountButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.deleteAccountButton.setMinimumSize(QtCore.QSize(0, 30))
        self.deleteAccountButton.setMaximumSize(QtCore.QSize(125, 16777215))
        self.deleteAccountButton.setObjectName("deleteAccountButton")
        self.horizontalLayout_3.addWidget(self.deleteAccountButton)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.scrollArea = QtWidgets.QScrollArea(self.horizontalLayoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 479, 527))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.enterButton.setText(_translate("MainWindow", "Выход"))
        self.changeLoginButton.setText(_translate("MainWindow", "Изменить логин"))
        self.changePasswordButton.setText(_translate("MainWindow", "Изменить пароль"))
        self.saveButton.setText(_translate("MainWindow", "Сохранить"))
        self.deleteButton.setText(_translate("MainWindow", "Удалить"))
        self.deleteAccountButton.setText(_translate("MainWindow", "Удалить аккаунт"))
